### ISSUE TITLE
Using a fuse root

### ISSUE THREAD

**Issue by fishrockz** [souk4711/hakoniwa#3]
Hi

I have the start of a basic filesystem written in rust on top of the fuser rust wrappers for fuse3

I would like to combine that code with something that uses your code to isolate a proccess to run in the file system i provide

I mount my file system at  "/home/will/projects/buildsystems/yaba/hi" and i can run commands that interact with that fs, i can also run the commands in "/home/will/projects/buildsystems/yaba/hi/usr/bin/" 

eg

```bash
sh-5.2$ /home/will/projects/buildsystems/yaba/hi/usr/bin/ls
Cargo.lock  Cargo.toml	examples  hi  Readme.md  src  target
```

I looked at your examples and i cant find something that effectively pivot roots so  had a go with the following

```rust
    sandbox.with_policy(SandboxPolicy::from_str(
        r#"
mounts = [
  { source = "/home/will/projects/buildsystems/yaba/hi"  , target = "/"  },
]
    "#,
    ).unwrap());
```

https://gitlab.com/girderstream/yet-another-build-app/-/commit/9c13a7646f1ec6d2d082ba6123a292245c00b6af#4ad8bc8a608cd170d23921a8583c12f260dbcf58_0_54

[2024-04-21T18:31:28Z INFO  hakoniwa::executor] Result: {"status":"SE","reason":"mount(Some(\"/home/will/projects/buildsystems/yaba/hi\"), \"\", None, MS_RDONLY | MS_NOSUID | MS_BIND | MS_REC, None) => ENOENT: No such file or directory","exit_code":null,"start_time":null,"real_time":null,"system_time":null,"user_time":null,"max_rss":null}

thread 'main' panicked at src/bin/yaba-exe.rs:72:5:
assertion `left == right` failed
  left: SandboxSetupError
 right: Ok

I will keep looking but i wondered if i was doing something obviously wrong?

**Comment by fishrockz** [comment]
@souk4711  thank you for the prompt reply

I did try as your suggestion of putting each folder as a mount but i could not get it to work.

I ended up creating a very simple patch that removed the tmp dir you use for root and to hard code it to use the location of my sysroot. This only works when its a absolute path.

I will try and workout how pass this value in as a optional perpetrator falling back to your temp dir method if not give.

Does this seem like a good approach to you?

Your lib seems rather nice so it would be nice to be able to contribute back if you would like the patch?

**Comment by fishrockz** [comment]
I had ago at fixing this before looking at the issue and seeing that you had completed it already, https://github.com/fishrockz/hakoniwa/commit/bae7c65c1f953e60f69081fc14f72cb41bae4341 my solution was a bit annoying and had more unwraps than i was happy with.

Your solution looks nice :)

The only thing i would note is that i think the path needs to be absolute for the sys calls to work nice.

```
 exit "" "hakoniwa: umount2(\"/.old_proc\", MNT_DETACH) => ENOENT: No such file or directory\n"
thread 'main' panicked at src/bin/yaba-exe.rs:84:5:
```

This is not very helpful when debugging but if you put the absolute path check in then you wont get the issue.
